export const productData = [
    {
      id: 1,
      name: 'Vestido Casual de Shein',
      description: 'Vestido ligero y cómodo para el verano.',
      price: 12990,
      image: '/images/vestido.png',
    },
    {
      id: 2,
      name: 'Blusa Elegante de Shein',
      description: 'Blusa ideal para ocasiones formales.',
      price: 15990,
      image: '/images/blusa.png',
    },
    {
      id: 3,
      name: 'Jeans de Shein',
      description: 'Jeans sueltos tipo cargo cómodos.',
      price: 17990,
      image: '/images/jeans.png',
    },
    {
      id: 4,
      name: 'Chaqueta de Shein',
      description: 'Chaqueta para clima frío.',
      price: 24990,
      image: '/images/chaqueta.png',
    },
    {
      id: 5,
      name: 'Vestido Casual de Shein',
      description: 'Vestido ligero y cómodo para el verano.',
      price: 12990,
      image: '/images/vestido.png',
    },
    {
      id: 6,
      name: 'Blusa Elegante de Shein',
      description: 'Blusa ideal para ocasiones formales.',
      price: 15990,
      image: '/images/blusa.png',
    },
    {
      id: 7,
      name: 'Jeans de Shein',
      description: 'Jeans sueltos tipo cargo cómodos.',
      price: 17990,
      image: '/images/jeans.png',
    },
    {
      id: 8,
      name: 'Chaqueta de Shein',
      description: 'Chaqueta para clima frío.',
      price: 24990,
      image: '/images/chaqueta.png',
    },
    {
      id: 9,
      name: 'Vestido Casual de Shein',
      description: 'Vestido ligero y cómodo para el verano.',
      price: 12990,
      image: '/images/vestido.png',
    },
    {
      id: 10,
      name: 'Blusa Elegante de Shein',
      description: 'Blusa ideal para ocasiones formales.',
      price: 15990,
      image: '/images/blusa.png',
    },
    {
      id: 11,
      name: 'Jeans de Shein',
      description: 'Jeans sueltos tipo cargo cómodos.',
      price: 17990,
      image: '/images/jeans.png',
    },
    {
      id: 12,
      name: 'Chaqueta de Shein',
      description: 'Chaqueta para clima frío.',
      price: 24990,
      image: '/images/chaqueta.png',
    },
    {
      id: 13,
      name: 'Vestido Casual de Shein',
      description: 'Vestido ligero y cómodo para el verano.',
      price: 12990,
      image: '/images/vestido.png',
    },
    {
      id: 14,
      name: 'Blusa Elegante de Shein',
      description: 'Blusa ideal para ocasiones formales.',
      price: 15990,
      image: '/images/blusa.png',
    },
    {
      id: 15,
      name: 'Jeans de Shein',
      description: 'Jeans sueltos tipo cargo cómodos.',
      price: 17990,
      image: '/images/jeans.png',
    },
    {
      id: 16,
      name: 'Chaqueta de Shein',
      description: 'Chaqueta para clima frío.',
      price: 24990,
      image: '/images/chaqueta.png',
    },
    {
      id: 17,
      name: 'Vestido Casual de Shein',
      description: 'Vestido ligero y cómodo para el verano.',
      price: 12990,
      image: '/images/vestido.png',
    },
    {
      id: 18,
      name: 'Blusa Elegante de Shein',
      description: 'Blusa ideal para ocasiones formales.',
      price: 15990,
      image: '/images/blusa.png',
    },
    {
      id: 19,
      name: 'Jeans de Shein',
      description: 'Jeans sueltos tipo cargo cómodos.',
      price: 17990,
      image: '/images/jeans.png',
    },
    {
      id: 20,
      name: 'Chaqueta de Shein',
      description: 'Chaqueta para clima frío.',
      price: 24990,
      image: '/images/chaqueta.png',
    },
    {
      id: 21,
      name: 'Vestido Casual de Shein',
      description: 'Vestido ligero y cómodo para el verano.',
      price: 12990,
      image: '/images/vestido.png',
    },
    {
      id: 22,
      name: 'Blusa Elegante de Shein',
      description: 'Blusa ideal para ocasiones formales.',
      price: 15990,
      image: '/images/blusa.png',
    },
    {
      id: 23,
      name: 'Jeans de Shein',
      description: 'Jeans sueltos tipo cargo cómodos.',
      price: 17990,
      image: '/images/jeans.png',
    },
    {
      id: 24,
      name: 'Chaqueta de Shein',
      description: 'Chaqueta para clima frío.',
      price: 24990,
      image: '/images/chaqueta.png',
    },
    {
      id: 25,
      name: 'Chaqueta de Shein',
      description: 'Chaqueta para clima frío.',
      price: 24990,
      image: '/images/chaqueta.png',
    },
  ];
  